#!/bin/bash
# Smart Firewall Setup Script
# Run once on any new machine: bash ~/sfw/setup.sh

set -e

ENV_FILE="$(dirname "$0")/.env"
echo ""
echo "============================================"
echo "  SMART FIREWALL — SETUP"
echo "============================================"
echo ""

# Detect network interface automatically
DETECTED=$(ip route | grep default | awk '{print $5}' | head -1)
if [ -z "$DETECTED" ]; then
    DETECTED=$(ip link | grep -E "^[0-9]+: (en|eth|ens)" | awk -F': ' '{print $2}' | head -1)
fi

echo "Available network interfaces:"
ip link | grep -E "^[0-9]+:" | awk -F': ' '{print "  " $2}'
echo ""
read -p "Network interface to monitor [$DETECTED]: " IFACE
IFACE=${IFACE:-$DETECTED}

echo ""
read -p "Your Node ID (unique name for this machine, e.g. animesh-node): " NODE_ID
NODE_ID=${NODE_ID:-$(hostname)}

echo ""
echo "Firebase setup (press Enter to skip if not using cloud sync):"
read -p "Firebase DB URL (e.g. https://xxx.firebasedatabase.app): " FB_URL
read -p "Path to serviceAccountKey.json: " FB_CREDS
FB_CREDS=${FB_CREDS:-$(dirname "$0")/agent/serviceAccountKey.json}

echo ""
cat > "$ENV_FILE" << ENV
# Smart Firewall Configuration
# Generated by setup.sh on $(date)

SFW_INTERFACE=$IFACE
SFW_CLIENT_ID=$NODE_ID

FIREBASE_DB_URL=$FB_URL
FIREBASE_CREDS=$FB_CREDS
ENV

echo "============================================"
echo "  Config saved to: $ENV_FILE"
echo ""
echo "  Interface : $IFACE"
echo "  Node ID   : $NODE_ID"
echo "  Firebase  : ${FB_URL:-disabled}"
echo "============================================"
echo ""

# Create venv if it doesn't exist
if [ ! -d "$(dirname "$0")/venv" ]; then
    echo "Creating Python virtual environment..."
    python3 -m venv "$(dirname "$0")/venv"
    "$(dirname "$0")/venv/bin/pip" install --quiet --upgrade pip
    "$(dirname "$0")/venv/bin/pip" install --quiet -r "$(dirname "$0")/requirements.txt"
    echo "Dependencies installed."
fi

echo ""
echo "Setup complete. Run the firewall with:"
echo "  sudo $(dirname "$0")/venv/bin/python3 $(dirname "$0")/agent/main.py"
echo ""
